source("getData.R")
powerData <- getPowerData()
png("plot2.png", width = 480, height = 480)
with(powerData, plot(Time,Global_active_power,type = "l", ylab = "Global Active Power(kilowatts)", xlab = ""))
dev.off()